# Generated by Django 2.2.17 on 2020-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='avk',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
